source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc


gem 'jquery-turbolinks'

# Bootstrap para rails
gem "therubyracer"
gem "less-rails"#Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "twitter-bootstrap-rails"
gem 'devise-bootstrap-views'


# Funcionamiento de backend
gem 'devise'
gem 'pundit'

#validar correo
gem 'email_validator'

#Paginador de tablas
#gem 'will_paginate'

# Manage aws s3 storage
#gem "aws-sdk"
#gem 'aws-sdk', '~> 2'
gem 'aws-sdk', '< 2.0'

# Manejo de archivos adjuntos
gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"

# Manejo conversion de archivos
gem "paperclip-ffmpeg"

# Fires background process for conversion
gem "delayed_paperclip"

# Manage queue of background processes
gem "sidekiq"

# figaro for env vars
gem "figaro"

#ckeditor para el blog
gem 'ckeditor', github: 'galetahub/ckeditor'

#kaminari para paginacion
gem 'kaminari'

#gem 'wkhtmltopdf-binary'

gem 'pdfkit'

gem 'httparty'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Gem to migrate the db and add seeds
gem 'migration_data'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'rack-utf8_sanitizer'
gem 'tzinfo-data',platforms: [:mingw, :mswin]
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  gem "better_errors"
  gem "binding_of_caller"

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console'

  gem 'rails-erd'

  #gem 'httparty'

  #gem 'jquery-turbolinks'

  
end

group :test, :production do
  gem 'pg'

  #gem 'jquery-turbolinks'
  #gem 'httparty'
  
end

